### ISSUE TITLE
请问作者有没有发现ReadProcessMemory方法不稳定问题

### ISSUE THREAD

**Issue by MethodJiao** [rrrrrrri/MyEtGTrainer#1]
在电脑开了很多的程序时候第一次基址+偏移 ReadProcessMemory 偶发getlasterror 299失败。我尝试了很多办法没有解决，希望作者能提供思路排查。我目前发现重启电脑后100%能恢复，但是如果用了一段时间后依旧偶发失败，但是同参数下CE修改器始终正常，就第一次ReadProcessMemory不稳定

**Comment by rrrrrrri** [comment]
抱歉，工具是我业余时间出于学习目的编写的，我对 Winapi 没有特别深入的了解。299 应该是 ReadProcessMemory 仅完成一部分读取请求，或许访问到了非法内存？我觉得可以调试一下此处看看是否出现访存错误，再确认一下基址和偏移是否指向了正确的地址。

**Comment by rrrrrrri** [comment]
This issue will be closed if you do not have further questions.
